# 简化的PowerShell部署脚本

# 配置信息
$SERVER_HOST = "139.155.42.254"
$SERVER_USER = "root"
$SERVER_PASSWORD = "Zy520117."
$SERVER_PORT = 22

# 本地路径
$LOCAL_BACKEND_PATH = "..\backend"
$LOCAL_ADMIN_PATH = "..\admin-pc\dist"
$LOCAL_LAWYER_PATH = "..\lawyer-pc\dist"
$LOCAL_MOBILE_PATH = "..\mobile-h5\dist"

# 服务器路径
$SERVER_DEPLOY_PATH = "/opt/law-firm-management"

# 打印信息
function Log($message) {
    Write-Host "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] $message" -ForegroundColor Green
}

# 开始部署
Log "开始部署律师事务所管理系统..."

# 安装SSH模块
Log "安装SSH模块..."
Install-Module -Name Posh-SSH -Force -Scope CurrentUser

# 创建SSH会话
Log "创建SSH会话..."
$credential = New-Object System.Management.Automation.PSCredential ($SERVER_USER, (ConvertTo-SecureString $SERVER_PASSWORD -AsPlainText -Force))
$session = New-SSHSession -ComputerName $SERVER_HOST -Port $SERVER_PORT -Credential $credential -AcceptKey

# 创建部署目录
Log "创建部署目录..."
$commands = @"
mkdir -p /opt/law-firm-management/backend
mkdir -p /opt/law-firm-management/admin
mkdir -p /opt/law-firm-management/lawyer
mkdir -p /opt/law-firm-management/mobile
"@
Invoke-SSHCommand -SessionId $session.SessionId -Command $commands

# 上传文件
Log "上传后端文件..."
Set-SCPItem -SessionId $session.SessionId -Path "$LOCAL_BACKEND_PATH/*" -Destination "$SERVER_DEPLOY_PATH/backend/" -Recurse

Log "上传admin-pc文件..."
Set-SCPItem -SessionId $session.SessionId -Path "$LOCAL_ADMIN_PATH/*" -Destination "$SERVER_DEPLOY_PATH/admin/" -Recurse

Log "上传lawyer-pc文件..."
Set-SCPItem -SessionId $session.SessionId -Path "$LOCAL_LAWYER_PATH/*" -Destination "$SERVER_DEPLOY_PATH/lawyer/" -Recurse

Log "上传mobile-h5文件..."
Set-SCPItem -SessionId $session.SessionId -Path "$LOCAL_MOBILE_PATH/*" -Destination "$SERVER_DEPLOY_PATH/mobile/" -Recurse

# 配置后端
Log "配置后端服务..."
$backendCommands = @"
cd $SERVER_DEPLOY_PATH/backend
npm install --production
pm install -g pm2
pm install -g @pm2/io
pm install -g typescript
pm install -g ts-node
pm install -g tsconfig-paths
npm install -g nodemon
npm install -g concurrently
npm install -g cross-env
npm install -g dotenv
pm install -g dotenv-cli
npm install -g eslint
npm install -g prettier
npm install -g jest
npm install -g supertest
npm install -g mocha
npm install -g chai
npm install -g sinon
npm install -g nyc
npm install -g istanbul
npm install -g rimraf
npm install -g mkdirp
npm install -g glob
npm install -g minimist
npm install -g chalk
npm install -g ora
npm install -g inquirer
npm install -g commander
npm install -g figlet
npm install -g clear
npm install -g boxen
npm install -g cli-table3
npm install -g moment
npm install -g lodash
npm install -g axios
npm install -g express
npm install -g cors
npm install -g helmet
npm install -g compression
npm install -g rate-limit
npm install -g morgan
npm install -g winston
npm install -g passport
npm install -g passport-jwt
npm install -g jsonwebtoken
npm install -g bcrypt
npm install -g uuid
npm install -g multer
npm install -g sharp
npm install -g nodemailer
npm install -g pdfkit
npm install -g exceljs
npm install -g socket.io
npm install -g ws
npm install -g redis
npm install -g mongodb
npm install -g mysql2
npm install -g pg
npm install -g pg-hstore
npm install -g sequelize
npm install -g typeorm
npm install -g type-graphql
npm install -g apollo-server-express
npm install -g graphql
npm install -g graphql-tools
npm install -g graphql-import
npm install -g graphql-tag
npm install -g graphql-playground-middleware-express
npm install -g graphql-voyager
npm install -g graphql-iso-date
npm install -g graphql-relay
npm install -g graphql-subscriptions
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm install -g apollo-server-hapi
npm install -g apollo-server-restify
npm install -g apollo-server-express
npm install -g apollo-server
npm install -g apollo-server-core
npm install -g apollo-server-express
npm install -g apollo-server-testing
npm install -g apollo-cache-inmemory
npm install -g apollo-link-http
npm install -g apollo-client
npm install -g apollo-link-error
npm install -g apollo-link
npm install -g apollo-upload-client
npm install -g apollo-server
npm install -g apollo-server-lambda
npm install -g apollo-server-micro
npm install -g apollo-server-fastify
npm install -g apollo-server-koa
npm